version: '3.8'

services:
  oracledb19c_new:
    image: doctorkirk/oracle-19c
    container_name: oracledb19c_new
    volumes:
      - oracle-data:/opt/oracle/oradata
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=Password123
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - 1521:1521
      - 5500:5500
    healthcheck:
      test: ["CMD-SHELL", "pgrep pmon"]
      interval: 10s
      timeout: 5s
      retries: 10

  web:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: web
    ports:
      - 8080:8000
    depends_on:
      oracledb19c_new:
        condition: service_healthy
    command: >
      /wait-for-oracle.sh oracledb19c_new 1521 ORCLCDB rentastay 123456 &&
      python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      - ORACLE_HOST=oracledb19c_new
      - ORACLE_PORT=1521
      - ORACLE_SID=ORCLCDB
      - ORACLE_USER=rentastay
      - ORACLE_PASSWORD=123456

volumes:
  oracle-data: