-- Conectar a Usuario Rentastay
CONNECT rentastay/123456@ORCLCDB;
-- Insert Regions
INSERT INTO REGIONS (REGION_NAME) VALUES ('Región de Arica y Parinacota');
INSERT INTO REGIONS (REGION_NAME) VALUES ('Región de Tarapacá');
INSERT INTO REGIONS (REGION_NAME) VALUES ('Región de Antofagasta');
INSERT INTO REGIONS (REGION_NAME) VALUES ('Región de Atacama');
INSERT INTO REGIONS (REGION_NAME) VALUES ('Región de Coquimbo');
INSERT INTO REGIONS (REGION_NAME) VALUES ('Región de Valparaíso');
INSERT INTO REGIONS (REGION_NAME) VALUES ('Región Metropolitana de Santiago');
INSERT INTO REGIONS (REGION_NAME) VALUES ('Región O''Higgins');
INSERT INTO REGIONS (REGION_NAME) VALUES ('Región del Maule');
INSERT INTO REGIONS (REGION_NAME) VALUES ('Región de Ñuble');
INSERT INTO REGIONS (REGION_NAME) VALUES ('Región del Biobío');
INSERT INTO REGIONS (REGION_NAME) VALUES ('Región de La Araucanía');
INSERT INTO REGIONS (REGION_NAME) VALUES ('Región de Los Ríos');
INSERT INTO REGIONS (REGION_NAME) VALUES ('Región de Los Lagos');
INSERT INTO REGIONS (REGION_NAME) VALUES ('Región de Aysén');
INSERT INTO REGIONS (REGION_NAME) VALUES ('Región de Magallanes');

-- Insert Comunas (principales ciudades de Chile)
INSERT INTO COMUNAS (COMUNA_NAME, REGION_ID) VALUES ('Arica', 1);
INSERT INTO COMUNAS (COMUNA_NAME, REGION_ID) VALUES ('Iquique', 2);
INSERT INTO COMUNAS (COMUNA_NAME, REGION_ID) VALUES ('Antofagasta', 3);
INSERT INTO COMUNAS (COMUNA_NAME, REGION_ID) VALUES ('Copiapó', 4);
INSERT INTO COMUNAS (COMUNA_NAME, REGION_ID) VALUES ('La Serena', 5);
INSERT INTO COMUNAS (COMUNA_NAME, REGION_ID) VALUES ('Valparaíso', 6);
INSERT INTO COMUNAS (COMUNA_NAME, REGION_ID) VALUES ('Santiago', 7);
INSERT INTO COMUNAS (COMUNA_NAME, REGION_ID) VALUES ('Rancagua', 8);
INSERT INTO COMUNAS (COMUNA_NAME, REGION_ID) VALUES ('Talca', 9);
INSERT INTO COMUNAS (COMUNA_NAME, REGION_ID) VALUES ('Chillán', 10);
INSERT INTO COMUNAS (COMUNA_NAME, REGION_ID) VALUES ('Concepción', 11);
INSERT INTO COMUNAS (COMUNA_NAME, REGION_ID) VALUES ('Temuco', 12);
INSERT INTO COMUNAS (COMUNA_NAME, REGION_ID) VALUES ('Valdivia', 13);
INSERT INTO COMUNAS (COMUNA_NAME, REGION_ID) VALUES ('Puerto Montt', 14);
INSERT INTO COMUNAS (COMUNA_NAME, REGION_ID) VALUES ('Coyhaique', 15);
INSERT INTO COMUNAS (COMUNA_NAME, REGION_ID) VALUES ('Punta Arenas', 16);

-- Comunas adicionales para la Región Metropolitana
INSERT INTO COMUNAS (COMUNA_NAME, REGION_ID) VALUES ('Puente Alto', 7);
INSERT INTO COMUNAS (COMUNA_NAME, REGION_ID) VALUES ('Maipú', 7);
INSERT INTO COMUNAS (COMUNA_NAME, REGION_ID) VALUES ('La Florida', 7);
INSERT INTO COMUNAS (COMUNA_NAME, REGION_ID) VALUES ('Las Condes', 7);
INSERT INTO COMUNAS (COMUNA_NAME, REGION_ID) VALUES ('Quilicura', 7);

COMMIT;