-- Insert Countries
INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('Chile');

--Insert States (Regiones de Chile)
INSERT INTO STATES (STATE_NAME, COUNTRY_NAME) VALUES ('Región de Arica y Parinacota', 'Chile');
INSERT INTO STATES (STATE_NAME, COUNTRY_NAME) VALUES ('Región de Tarapacá', 'Chile');
INSERT INTO STATES (STATE_NAME, COUNTRY_NAME) VALUES ('Región de Antofagasta', 'Chile');
INSERT INTO STATES (STATE_NAME, COUNTRY_NAME) VALUES ('Región de Atacama', 'Chile');
INSERT INTO STATES (STATE_NAME, COUNTRY_NAME) VALUES ('Región de Coquimbo', 'Chile');
INSERT INTO STATES (STATE_NAME, COUNTRY_NAME) VALUES ('Región de Valparaíso', 'Chile');
INSERT INTO STATES (STATE_NAME, COUNTRY_NAME) VALUES ('Región Metropolitana de Santiago', 'Chile');
INSERT INTO STATES (STATE_NAME, COUNTRY_NAME) VALUES ('Región del Libertador General Bernardo O''Higgins', 'Chile');
INSERT INTO STATES (STATE_NAME, COUNTRY_NAME) VALUES ('Región del Maule', 'Chile');
INSERT INTO STATES (STATE_NAME, COUNTRY_NAME) VALUES ('Región de Ñuble', 'Chile');
INSERT INTO STATES (STATE_NAME, COUNTRY_NAME) VALUES ('Región del Biobío', 'Chile');
INSERT INTO STATES (STATE_NAME, COUNTRY_NAME) VALUES ('Región de La Araucanía', 'Chile');
INSERT INTO STATES (STATE_NAME, COUNTRY_NAME) VALUES ('Región de Los Ríos', 'Chile');
INSERT INTO STATES (STATE_NAME, COUNTRY_NAME) VALUES ('Región de Los Lagos', 'Chile');
INSERT INTO STATES (STATE_NAME, COUNTRY_NAME) VALUES ('Región de Aysén del General Carlos Ibáñez del Campo', 'Chile');
INSERT INTO STATES (STATE_NAME, COUNTRY_NAME) VALUES ('Región de Magallanes y de la Antártica Chilena', 'Chile');

-- Insert Cities (Principales ciudades de Chile)
INSERT INTO CITIES (CITY_NAME, STATE_ID) VALUES ('Arica', 1);
INSERT INTO CITIES (CITY_NAME, STATE_ID) VALUES ('Iquique', 2);
INSERT INTO CITIES (CITY_NAME, STATE_ID) VALUES ('Antofagasta', 3);
INSERT INTO CITIES (CITY_NAME, STATE_ID) VALUES ('Copiapó', 4);
INSERT INTO CITIES (CITY_NAME, STATE_ID) VALUES ('La Serena', 5);
INSERT INTO CITIES (CITY_NAME, STATE_ID) VALUES ('Valparaíso', 6);
INSERT INTO CITIES (CITY_NAME, STATE_ID) VALUES ('Santiago', 7);
INSERT INTO CITIES (CITY_NAME, STATE_ID) VALUES ('Rancagua', 8);
INSERT INTO CITIES (CITY_NAME, STATE_ID) VALUES ('Talca', 9);
INSERT INTO CITIES (CITY_NAME, STATE_ID) VALUES ('Chillán', 10);
INSERT INTO CITIES (CITY_NAME, STATE_ID) VALUES ('Concepción', 11);
INSERT INTO CITIES (CITY_NAME, STATE_ID) VALUES ('Temuco', 12);
INSERT INTO CITIES (CITY_NAME, STATE_ID) VALUES ('Valdivia', 13);
INSERT INTO CITIES (CITY_NAME, STATE_ID) VALUES ('Puerto Montt', 14);
INSERT INTO CITIES (CITY_NAME, STATE_ID) VALUES ('Coyhaique', 15);
INSERT INTO CITIES (CITY_NAME, STATE_ID) VALUES ('Punta Arenas', 16);

-- Ciudades adicionales para la Región Metropolitana
INSERT INTO CITIES (CITY_NAME, STATE_ID) VALUES ('Puente Alto', 7);
INSERT INTO CITIES (CITY_NAME, STATE_ID) VALUES ('Maipú', 7);
INSERT INTO CITIES (CITY_NAME, STATE_ID) VALUES ('La Florida', 7);
INSERT INTO CITIES (CITY_NAME, STATE_ID) VALUES ('Las Condes', 7);
INSERT INTO CITIES (CITY_NAME, STATE_ID) VALUES ('Quilicura', 7);

COMMIT;